import type { User, Idea, PortfolioPosition, VoteMap, AuditEntry, Session, GamingFlag, TickerItem } from './types';

export const USERS: User[] = [
  { id: 'arun.john', email: 'arun@century.ae', name: 'Arun Leslie John', title: 'Chief Market Analyst', role: 'CIO', tier: 'A+', hitRate: 73, avgRet: 18.4, sharpe: 1.82, drawCtrl: 91, consistency: 88, peerScore: 94, ideaScore: 88, allocScore: 92, researchScore: 91 },
  { id: 'bhavik.mehta', email: 'bhavik@century.ae', name: 'Bhavik Mehta', title: 'Deputy Head Research', role: 'PM', tier: 'A+', hitRate: 71, avgRet: 16.2, sharpe: 1.74, drawCtrl: 88, consistency: 85, peerScore: 90, ideaScore: 85, allocScore: 90, researchScore: 88 },
  { id: 'deepa.sachanandani', email: 'deepa@century.ae', name: 'Deepa Sachanandani', title: 'Deputy Head Research', role: 'PM', tier: 'A+', hitRate: 65, avgRet: 14.1, sharpe: 1.58, drawCtrl: 82, consistency: 79, peerScore: 84, ideaScore: 79, allocScore: 84, researchScore: 82 },
  { id: 'meyyappan.lakshmanan', email: 'meyyappan@century.ae', name: 'Meyyappan Lakshmanan', title: 'Sr. Research Analyst', role: 'PM', tier: 'A', hitRate: 68, avgRet: 15.3, sharpe: 1.65, drawCtrl: 85, consistency: 82, peerScore: 86, ideaScore: 82, allocScore: 78, researchScore: 83 },
  { id: 'intissar.elkhadiri', email: 'intissar@century.ae', name: 'Intissar El Khadiri', title: 'Senior Research Analyst', role: 'PM', tier: 'A', hitRate: 63, avgRet: 13.8, sharpe: 1.45, drawCtrl: 80, consistency: 76, peerScore: 81, ideaScore: 76, allocScore: 81, researchScore: 78 },
  { id: 'dnyanada.kulkarni', email: 'dnyanada.k@century.ae', name: 'Dnyanada Kulkarni', title: 'Senior Research Analyst', role: 'PM', tier: 'A', hitRate: 61, avgRet: 12.9, sharpe: 1.38, drawCtrl: 78, consistency: 73, peerScore: 77, ideaScore: 73, allocScore: 75, researchScore: 75 },
  { id: 'jagpavit.bhurjee', email: 'jagpavit.bhurjee@century.ae', name: 'Jagpavit Bhurjee', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 55, avgRet: 10.2, sharpe: 1.12, drawCtrl: 70, consistency: 65, peerScore: 68, ideaScore: 64, allocScore: 68, researchScore: 66 },
  { id: 'saakshi.shingare', email: 'saakshi.shingare@century.ae', name: 'Saakshi Shingare', title: 'Research Analyst', role: 'PM', tier: 'A', hitRate: 62, avgRet: 13.1, sharpe: 1.41, drawCtrl: 79, consistency: 74, peerScore: 80, ideaScore: 74, allocScore: 72, researchScore: 75 },
  { id: 'devanshi.agrawal', email: 'devanshi.agrawal@centuryiq.in', name: 'Devanshi Agrawal', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 52, avgRet: 9.4, sharpe: 1.05, drawCtrl: 66, consistency: 62, peerScore: 64, ideaScore: 61, allocScore: 63, researchScore: 62 },
  { id: 'labiba.angona', email: 'labiba.angona@century.ae', name: 'Labiba Zoha Angona', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 57, avgRet: 11.3, sharpe: 1.21, drawCtrl: 72, consistency: 68, peerScore: 71, ideaScore: 67, allocScore: 70, researchScore: 68 },
  { id: 'aditya.nambiar', email: 'aditya.nambiar@centuryiq.in', name: 'Aditya Nambiar', title: 'Research Analyst', role: 'PM', tier: 'A', hitRate: 60, avgRet: 12.5, sharpe: 1.38, drawCtrl: 77, consistency: 72, peerScore: 76, ideaScore: 72, allocScore: 74, researchScore: 73 },
  { id: 'fenil.gala', email: 'fenil.gala@centuryiq.in', name: 'Fenil Gala', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 53, avgRet: 9.8, sharpe: 1.08, drawCtrl: 67, consistency: 63, peerScore: 65, ideaScore: 62, allocScore: 61, researchScore: 62 },
  { id: 'kriti.toshniwal', email: 'kriti.toshniwal@centuryiq.in', name: 'Kriti Toshniwal', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 56, avgRet: 10.9, sharpe: 1.18, drawCtrl: 71, consistency: 66, peerScore: 69, ideaScore: 66, allocScore: 69, researchScore: 67 },
  { id: 'dhairya.jani', email: 'dhairya.jani@centuryiq.in', name: 'Dhairya Jani', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 44, avgRet: 7.2, sharpe: 0.87, drawCtrl: 55, consistency: 50, peerScore: 52, ideaScore: 52, allocScore: 55, researchScore: 53 },
  { id: 'vritti.shah', email: 'vritti.shah@century.ae', name: 'Vritti Shah', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 58, avgRet: 11.8, sharpe: 1.25, drawCtrl: 73, consistency: 69, peerScore: 72, ideaScore: 68, allocScore: 65, researchScore: 67 },
  { id: 'kashish.dhanani', email: 'kashish.dhanani@century.ae', name: 'Kashish Dhanani', title: 'Research Analyst', role: 'PM', tier: 'B', hitRate: 46, avgRet: 7.8, sharpe: 0.91, drawCtrl: 58, consistency: 53, peerScore: 55, ideaScore: 54, allocScore: 57, researchScore: 55 },
];

export const IDEAS0: Idea[] = [
  { id: 'IDEA-001', ticker: 'NVDA', assetClass: 'US Equities', dir: 'LONG', entry: 875.50, stop: 810.00, target: 1052.00, hold: '3-6M', posSize: 2.5, conv: 9, expRet: 20.2, expDD: -7.5, rr: 2.68, thesis: 'Dominant AI infrastructure play. Blackwell GPU ramp accelerating data center demand. CUDA moat unassailable with 85% market share. H200 supply constraints easing Q3.', catalysts: ['Q3 earnings beat', 'Blackwell ramp announcement', 'Azure/GCP capex expansion'], risks: ['Export restriction tightening', 'AMD MI300X share gains', 'Valuation compression'], authorId: 'meyyappan.lakshmanan', submittedAt: '2025-06-23T09:15Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 3420, rank: 1, pmScore: 91.2, skillScore: 87.5, rrScore: 89.3, quantScore: 85.1, finalScore: 89.1, momentumScore: 88, rsScore: 91, earningRevScore: 85, approvalStatus: 'APPROVED' },
  { id: 'IDEA-002', ticker: 'MSFT', assetClass: 'US Equities', dir: 'LONG', entry: 425.20, stop: 398.00, target: 490.00, hold: '2-4M', posSize: 3.0, conv: 8, expRet: 15.2, expDD: -6.4, rr: 2.38, thesis: 'Copilot monetization exceeding expectations. Azure AI services driving 28%+ cloud revenue growth. Enterprise AI adoption at inflection point with Fabric platform gaining traction.', catalysts: ['Azure AI revenue acceleration', 'Copilot enterprise penetration', 'FY26 guidance raise'], risks: ['Google Workspace competition', 'Macro slowdown in enterprise spend', 'OpenAI dependency'], authorId: 'saakshi.shingare', submittedAt: '2025-06-23T10:30Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 2850, rank: 2, pmScore: 85.3, skillScore: 82.1, rrScore: 85.7, quantScore: 83.4, finalScore: 84.2, momentumScore: 82, rsScore: 87, earningRevScore: 90, approvalStatus: 'APPROVED' },
  { id: 'IDEA-003', ticker: 'META', assetClass: 'US Equities', dir: 'LONG', entry: 520.80, stop: 478.00, target: 630.00, hold: '4-8M', posSize: 2.0, conv: 8, expRet: 21.0, expDD: -8.2, rr: 2.56, thesis: 'Llama 3 driving advertising efficiency gains 18%+ YoY. Threads monetization unlocking new TAM. Reality Labs losses stabilizing at ~$5B/qtr.', catalysts: ['Ad revenue acceleration Q3', 'Threads MAU milestone', 'WhatsApp Business monetization'], risks: ['FTC antitrust action', 'TikTok regulation reversal', 'Reality Labs burn escalation'], authorId: 'intissar.elkhadiri', submittedAt: '2025-06-23T11:00Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 2640, rank: 3, pmScore: 83.7, skillScore: 80.9, rrScore: 86.2, quantScore: 81.5, finalScore: 82.8, momentumScore: 79, rsScore: 83, earningRevScore: 88, approvalStatus: 'APPROVED' },
  { id: 'IDEA-004', ticker: 'GS', assetClass: 'US Equities', dir: 'LONG', entry: 462.30, stop: 435.00, target: 520.00, hold: '2-3M', posSize: 1.5, conv: 7, expRet: 12.5, expDD: -5.9, rr: 2.12, thesis: 'IB revenue recovery accelerating with M&A pipeline at 3-year highs. Trading desk outperformance in volatile macro. Marcus consumer segment dragging less than feared.', catalysts: ['M&A fee recognition Q3-Q4', 'Fed rate cut cycle beneficiary', 'Trading revenue beat'], risks: ['Credit loss provisions', 'Regulatory capital requirements', 'Marcus consumer losses'], authorId: 'aditya.nambiar', submittedAt: '2025-06-23T13:45Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 1980, rank: 4, pmScore: 76.4, skillScore: 78.2, rrScore: 77.8, quantScore: 74.3, finalScore: 76.8, momentumScore: 74, rsScore: 78, earningRevScore: 76, approvalStatus: 'PENDING' },
  { id: 'IDEA-005', ticker: 'TSLA', assetClass: 'US Equities', dir: 'SHORT', entry: 248.50, stop: 275.00, target: 190.00, hold: '2-4M', posSize: 1.0, conv: 7, expRet: 23.5, expDD: -10.7, rr: 2.20, thesis: 'Margin compression continuing with EV price war intensifying globally. FSD still years from regulatory approval. BYD taking share in every market. Robotaxi hype priced in.', catalysts: ['Q2 delivery miss', 'FSD recall potential', 'BYD market share data'], risks: ['Robotaxi announcement beats', 'Short squeeze dynamics', 'Elon catalyst tweet'], authorId: 'labiba.angona', submittedAt: '2025-06-23T14:00Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 1840, rank: 5, pmScore: 74.8, skillScore: 71.5, rrScore: 75.2, quantScore: 72.8, finalScore: 73.9, momentumScore: 68, rsScore: 65, earningRevScore: 58, approvalStatus: 'PENDING' },
  { id: 'IDEA-006', ticker: 'AMZN', assetClass: 'US Equities', dir: 'LONG', entry: 195.40, stop: 182.00, target: 225.00, hold: '3-5M', posSize: 2.0, conv: 8, expRet: 15.2, expDD: -6.9, rr: 2.20, thesis: 'AWS re-acceleration to 22%+ growth driven by AI workloads. Advertising achieving Google-like margins. Retail profitability inflection with $10B+ operating income run rate.', catalysts: ['AWS backlog conversion', 'Prime Day revenue beat', 'Advertising margin expansion'], risks: ['Antitrust regulatory scrutiny', 'Capex expansion concerns', 'Retail macro headwinds'], authorId: 'dnyanada.kulkarni', submittedAt: '2025-06-23T15:30Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 1720, rank: 6, pmScore: 72.1, skillScore: 74.8, rrScore: 73.5, quantScore: 71.2, finalScore: 72.9, momentumScore: 76, rsScore: 79, earningRevScore: 82, approvalStatus: 'PENDING' },
  { id: 'IDEA-007', ticker: 'XOM', assetClass: 'US Equities', dir: 'SHORT', entry: 118.20, stop: 126.00, target: 98.00, hold: '3-6M', posSize: 1.0, conv: 6, expRet: 17.1, expDD: -6.6, rr: 2.59, thesis: 'Oil demand destruction accelerating from EV adoption. Pioneer synergies fully priced in. Permian cost curve under pressure from service inflation.', catalysts: ['Oil price breakdown below $75', 'EV adoption data surprise', 'OPEC+ agreement breakdown'], risks: ['Geopolitical supply disruption', 'Strong buyback program', 'Energy rotation trade'], authorId: 'jagpavit.bhurjee', submittedAt: '2025-06-24T09:00Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 1320, rank: 7, pmScore: 68.3, skillScore: 65.7, rrScore: 70.4, quantScore: 66.9, finalScore: 67.8, momentumScore: 62, rsScore: 58, earningRevScore: 55, approvalStatus: 'PENDING' },
  { id: 'IDEA-008', ticker: 'GOOGL', assetClass: 'US Equities', dir: 'LONG', entry: 178.60, stop: 165.00, target: 210.00, hold: '3-5M', posSize: 2.5, conv: 7, expRet: 17.6, expDD: -7.6, rr: 2.32, thesis: 'Search resilience underestimated. AI Overviews driving monetization of new query types. YouTube Shorts at parity. Waymo robotaxi fleet acceleration optionality.', catalysts: ['AI Overviews monetization', 'YouTube Q3 acceleration', 'Cloud growth re-acceleration'], risks: ['DOJ antitrust remedy severity', 'OpenAI search threat', 'Ad market softening'], authorId: 'vritti.shah', submittedAt: '2025-06-24T10:15Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 1280, rank: 8, pmScore: 67.5, skillScore: 70.2, rrScore: 68.9, quantScore: 68.4, finalScore: 68.6, momentumScore: 70, rsScore: 73, earningRevScore: 74, approvalStatus: 'REVIEW' },
  { id: 'IDEA-009', ticker: 'JPM', assetClass: 'US Equities', dir: 'LONG', entry: 215.40, stop: 200.00, target: 240.00, hold: '2-4M', posSize: 1.5, conv: 6, expRet: 11.4, expDD: -7.1, rr: 1.60, thesis: 'Fortress balance sheet for rate normalization. IB recovery underpriced. Consumer credit more resilient than consensus. Buyback authorization at record levels.', catalysts: ['NIM expansion from rate cuts', 'IB pipeline conversion', 'Buyback acceleration'], risks: ['Commercial real estate exposure', 'Consumer credit deterioration', 'Regulatory capital increases'], authorId: 'fenil.gala', submittedAt: '2025-06-24T11:30Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 980, rank: 9, pmScore: 63.2, skillScore: 62.8, rrScore: 60.5, quantScore: 63.7, finalScore: 62.7, momentumScore: 65, rsScore: 68, earningRevScore: 63, approvalStatus: 'REVIEW' },
  { id: 'IDEA-010', ticker: 'AAPL', assetClass: 'US Equities', dir: 'LONG', entry: 192.30, stop: 178.00, target: 220.00, hold: '4-6M', posSize: 2.0, conv: 6, expRet: 14.4, expDD: -7.4, rr: 1.94, thesis: 'Apple Intelligence super-cycle upgrade beginning. Services approaching $110B run rate. India manufacturing diversification de-risking supply chain concentration risk.', catalysts: ['iPhone 17 AI upgrade cycle', 'Services margin expansion', 'India production ramp'], risks: ['China revenue concentration', 'AI feature differentiation vs Samsung', 'App Store regulatory changes'], authorId: 'kriti.toshniwal', submittedAt: '2025-06-24T14:00Z', weekId: 'W26-2025', status: 'ACTIVE', totalCredits: 840, rank: 10, pmScore: 60.8, skillScore: 63.4, rrScore: 62.1, quantScore: 61.5, finalScore: 61.8, momentumScore: 63, rsScore: 66, earningRevScore: 67, approvalStatus: 'REVIEW' },
];

export const PORT0: PortfolioPosition[] = [
  { rank: 1, ideaId: 'IDEA-001', ticker: 'NVDA', dir: 'LONG', alloc: 15, expRet: 20.2, sector: 'Technology', beta: 1.42, pmOvr: false },
  { rank: 2, ideaId: 'IDEA-002', ticker: 'MSFT', dir: 'LONG', alloc: 15, expRet: 15.2, sector: 'Technology', beta: 0.91, pmOvr: false },
  { rank: 3, ideaId: 'IDEA-003', ticker: 'META', dir: 'LONG', alloc: 15, expRet: 21.0, sector: 'Technology', beta: 1.28, pmOvr: false },
  { rank: 4, ideaId: 'IDEA-004', ticker: 'GS', dir: 'LONG', alloc: 8, expRet: 12.5, sector: 'Financials', beta: 1.15, pmOvr: false },
  { rank: 5, ideaId: 'IDEA-005', ticker: 'TSLA', dir: 'SHORT', alloc: 8, expRet: 23.5, sector: 'Consumer', beta: 1.88, pmOvr: false },
  { rank: 6, ideaId: 'IDEA-006', ticker: 'AMZN', dir: 'LONG', alloc: 8, expRet: 15.2, sector: 'Technology', beta: 1.12, pmOvr: false },
  { rank: 7, ideaId: 'IDEA-007', ticker: 'XOM', dir: 'SHORT', alloc: 8, expRet: 17.1, sector: 'Energy', beta: 0.78, pmOvr: false },
  { rank: 8, ideaId: 'IDEA-008', ticker: 'GOOGL', dir: 'LONG', alloc: 8, expRet: 17.6, sector: 'Technology', beta: 1.05, pmOvr: false },
  { rank: 9, ideaId: 'IDEA-009', ticker: 'JPM', dir: 'LONG', alloc: 0, expRet: 11.4, sector: 'Financials', beta: 1.08, pmOvr: false },
  { rank: 10, ideaId: 'IDEA-010', ticker: 'AAPL', dir: 'LONG', alloc: 0, expRet: 14.4, sector: 'Technology', beta: 1.14, pmOvr: false },
];

export const VOTES0: VoteMap = {
  'IDEA-001': { 'saakshi.shingare': 300, 'devanshi.agrawal': 250, 'labiba.angona': 200, 'vritti.shah': 280, 'aditya.nambiar': 200, 'fenil.gala': 150, 'kashish.dhanani': 220, 'intissar.elkhadiri': 180, 'dnyanada.kulkarni': 240, 'jagpavit.bhurjee': 400 },
  'IDEA-002': { 'saakshi.shingare': 250, 'devanshi.agrawal': 180, 'dhairya.jani': 200, 'aditya.nambiar': 400, 'kriti.toshniwal': 150, 'kashish.dhanani': 180, 'dnyanada.kulkarni': 200, 'labiba.angona': 100, 'fenil.gala': 100, 'vritti.shah': 90 },
  'IDEA-003': { 'saakshi.shingare': 200, 'labiba.angona': 150, 'vritti.shah': 180, 'aditya.nambiar': 200, 'fenil.gala': 200, 'kriti.toshniwal': 180, 'meyyappan.lakshmanan': 180, 'dnyanada.kulkarni': 150, 'devanshi.agrawal': 200, 'kashish.dhanani': 200 },
  'IDEA-004': { 'saakshi.shingare': 100, 'devanshi.agrawal': 80, 'dhairya.jani': 100, 'vritti.shah': 120, 'kriti.toshniwal': 80, 'meyyappan.lakshmanan': 200, 'intissar.elkhadiri': 200, 'labiba.angona': 150, 'kashish.dhanani': 200, 'fenil.gala': 150 },
  'IDEA-005': { 'jagpavit.bhurjee': 100, 'saakshi.shingare': 50, 'devanshi.agrawal': 100, 'meyyappan.lakshmanan': 150, 'intissar.elkhadiri': 150, 'dnyanada.kulkarni': 100, 'labiba.angona': 100, 'vritti.shah': 200, 'aditya.nambiar': 200, 'kashish.dhanani': 190 },
  'IDEA-006': { 'jagpavit.bhurjee': 120, 'saakshi.shingare': 100, 'devanshi.agrawal': 500, 'labiba.angona': 100, 'dhairya.jani': 120, 'vritti.shah': 100, 'fenil.gala': 100, 'kriti.toshniwal': 100, 'kashish.dhanani': 120, 'intissar.elkhadiri': 160 },
  'IDEA-007': { 'saakshi.shingare': 50, 'devanshi.agrawal': 100, 'labiba.angona': 80, 'dhairya.jani': 870, 'vritti.shah': 50, 'intissar.elkhadiri': 50, 'dnyanada.kulkarni': 50, 'aditya.nambiar': 50, 'kriti.toshniwal': 20 },
  'IDEA-008': { 'jagpavit.bhurjee': 80, 'saakshi.shingare': 100, 'devanshi.agrawal': 80, 'dhairya.jani': 80, 'vritti.shah': 50, 'meyyappan.lakshmanan': 100, 'intissar.elkhadiri': 100, 'dnyanada.kulkarni': 100, 'kashish.dhanani': 90, 'labiba.angona': 100, 'aditya.nambiar': 300 },
  'IDEA-009': { 'jagpavit.bhurjee': 80, 'saakshi.shingare': 50, 'devanshi.agrawal': 80, 'dhairya.jani': 80, 'meyyappan.lakshmanan': 80, 'intissar.elkhadiri': 100, 'dnyanada.kulkarni': 60, 'aditya.nambiar': 50, 'kriti.toshniwal': 100, 'labiba.angona': 100, 'kashish.dhanani': 100 },
  'IDEA-010': { 'jagpavit.bhurjee': 120, 'saakshi.shingare': 50, 'devanshi.agrawal': 60, 'meyyappan.lakshmanan': 100, 'intissar.elkhadiri': 80, 'aditya.nambiar': 100, 'fenil.gala': 50, 'labiba.angona': 80, 'kashish.dhanani': 100, 'kriti.toshniwal': 100 },
};

export const AUDIT: AuditEntry[] = [
  { id: 'AUD-015', ts: '2025-06-24 16:42:18', userId: 'arun.john', action: 'TRADE_APPROVED', detail: 'IDEA-001 NVDA LONG approved for portfolio 15%', ip: '10.0.1.45', dev: 'WIN-WS-01', risk: 'LOW' },
  { id: 'AUD-014', ts: '2025-06-24 16:38:55', userId: 'bhavik.mehta', action: 'TRADE_APPROVED', detail: 'IDEA-002 MSFT LONG approved — allocation confirmed', ip: '10.0.1.52', dev: 'WIN-WS-02', risk: 'LOW' },
  { id: 'AUD-013', ts: '2025-06-24 16:35:12', userId: 'bhavik.mehta', action: 'TRADE_APPROVED', detail: 'IDEA-003 META LONG approved', ip: '10.0.1.52', dev: 'WIN-WS-02', risk: 'LOW' },
  { id: 'AUD-012', ts: '2025-06-24 15:22:10', userId: 'meyyappan.lakshmanan', action: 'IDEA_SUBMITTED', detail: 'IDEA-001 submitted (NVDA LONG / Conv:9 / RR:2.68)', ip: '10.0.1.67', dev: 'MAC-PRO-ML01', risk: 'LOW' },
  { id: 'AUD-011', ts: '2025-06-24 14:48:33', userId: 'saakshi.shingare', action: 'VOTE_CAST', detail: 'Credit allocation: 300cr IDEA-001, 250cr IDEA-003, 200cr IDEA-006, 150cr IDEA-008', ip: '10.0.1.83', dev: 'WIN-LT-SS01', risk: 'LOW' },
  { id: 'AUD-010', ts: '2025-06-24 14:15:22', userId: 'dhairya.jani', action: 'LOGIN_FAILED', detail: 'Failed login: invalid OTP code (attempt 2 of 3)', ip: '10.0.2.144', dev: 'UNKNOWN', risk: 'HIGH' },
  { id: 'AUD-009', ts: '2025-06-24 14:12:08', userId: 'dhairya.jani', action: 'LOGIN_FAILED', detail: 'Failed login: incorrect password', ip: '10.0.2.144', dev: 'UNKNOWN', risk: 'MEDIUM' },
  { id: 'AUD-008', ts: '2025-06-24 13:52:09', userId: 'intissar.elkhadiri', action: 'IDEA_SUBMITTED', detail: 'IDEA-003 submitted (META LONG / Conv:8 / RR:2.56)', ip: '10.0.1.71', dev: 'MAC-LT-IK01', risk: 'LOW' },
  { id: 'AUD-007', ts: '2025-06-24 13:30:44', userId: 'aditya.nambiar', action: 'VOTE_CAST', detail: 'Credit allocation: 400cr IDEA-002, 200cr IDEA-004, 200cr IDEA-001, 200cr IDEA-005', ip: '10.0.1.91', dev: 'WIN-LT-AN01', risk: 'MEDIUM' },
  { id: 'AUD-006', ts: '2025-06-24 12:18:55', userId: 'arun.john', action: 'PERMISSION_CHANGE', detail: 'User kashish.dhanani: tier update B→A submitted for review', ip: '10.0.1.45', dev: 'WIN-WS-01', risk: 'LOW' },
  { id: 'AUD-005', ts: '2025-06-24 11:45:30', userId: 'deepa.sachanandani', action: 'ALLOCATION_ADJUSTED', detail: 'IDEA-004 GS: position override 8%→6% (risk budget constraint)', ip: '10.0.1.58', dev: 'WIN-WS-03', risk: 'LOW' },
  { id: 'AUD-004', ts: '2025-06-24 10:22:18', userId: 'dnyanada.kulkarni', action: 'IDEA_SUBMITTED', detail: 'IDEA-006 submitted (AMZN LONG / Conv:8 / RR:2.20)', ip: '10.0.1.74', dev: 'WIN-WS-04', risk: 'LOW' },
  { id: 'AUD-003', ts: '2025-06-23 17:30:12', userId: 'arun.john', action: 'SESSION_TERMINATED', detail: 'Forced session termination: kriti.toshniwal — concurrent login from unrecognized device', ip: '10.0.1.45', dev: 'WIN-WS-01', risk: 'HIGH' },
  { id: 'AUD-002', ts: '2025-06-23 16:44:29', userId: 'kriti.toshniwal', action: 'LOGIN_ANOMALY', detail: 'Device fingerprint mismatch. Expected WIN-WORK-KT09, received MAC-HOME-KT. Session blocked.', ip: '172.16.0.22', dev: 'MAC-HOME-KT', risk: 'HIGH' },
  { id: 'AUD-001', ts: '2025-06-23 09:00:00', userId: 'arun.john', action: 'SESSION_STARTED', detail: 'Weekly cycle W26-2025 initiated. Credit reset: 1000cr distributed to 15 eligible analysts.', ip: '10.0.1.45', dev: 'WIN-WS-01', risk: 'LOW' },
];

export const SESSIONS: Session[] = [
  { userId: 'arun.john', name: 'Arun Leslie John', role: 'CIO', ip: '10.0.1.45', dev: 'WIN-WS-01', lastAct: '2m ago', status: 'ACTIVE', mfa: true, risk: 2 },
  { userId: 'bhavik.mehta', name: 'Bhavik Mehta', role: 'PM', ip: '10.0.1.52', dev: 'WIN-WS-02', lastAct: '8m ago', status: 'ACTIVE', mfa: true, risk: 3 },
  { userId: 'deepa.sachanandani', name: 'Deepa Sachanandani', role: 'PM', ip: '10.0.1.58', dev: 'WIN-WS-03', lastAct: '31m ago', status: 'IDLE', mfa: true, risk: 5 },
  { userId: 'meyyappan.lakshmanan', name: 'Meyyappan Lakshmanan', role: 'PM', ip: '10.0.1.67', dev: 'MAC-PRO-ML01', lastAct: '15m ago', status: 'ACTIVE', mfa: true, risk: 5 },
  { userId: 'saakshi.shingare', name: 'Saakshi Shingare', role: 'PM', ip: '10.0.1.83', dev: 'WIN-LT-SS01', lastAct: '3m ago', status: 'ACTIVE', mfa: true, risk: 8 },
  { userId: 'dhairya.jani', name: 'Dhairya Jani', role: 'PM', ip: '10.0.2.144', dev: 'UNKNOWN', lastAct: '52m ago', status: 'BLOCKED', mfa: false, risk: 87 },
  { userId: 'kriti.toshniwal', name: 'Kriti Toshniwal', role: 'PM', ip: '172.16.0.22', dev: 'MAC-HOME-KT', lastAct: '1h 14m ago', status: 'TERMINATED', mfa: true, risk: 64 },
  { userId: 'aditya.nambiar', name: 'Aditya Nambiar', role: 'PM', ip: '10.0.1.91', dev: 'WIN-LT-AN01', lastAct: '22m ago', status: 'ACTIVE', mfa: true, risk: 12 },
];

export const GAMING: GamingFlag[] = [
  { id: 'G-001', type: 'RECIPROCAL_VOTING', sev: 'HIGH', users: ['devanshi.agrawal', 'fenil.gala'], detail: 'Mutual voting pattern: 4/4 weeks bidirectional. Similarity coefficient 0.94.', score: 82, ts: '2025-06-24 14:22' },
  { id: 'G-002', type: 'VOTE_CONCENTRATION', sev: 'MEDIUM', users: ['dhairya.jani'], detail: '87% of weekly credits allocated to single idea IDEA-007. Peer median: 34%.', score: 58, ts: '2025-06-24 12:15' },
  { id: 'G-003', type: 'VOTING_RING', sev: 'HIGH', users: ['jagpavit.bhurjee', 'vritti.shah', 'kashish.dhanani'], detail: 'Triangular mutual support network detected. Voting similarity 91% over 6 weeks.', score: 76, ts: '2025-06-23 16:30' },
  { id: 'G-004', type: 'ANALYST_FAVORITISM', sev: 'LOW', users: ['intissar.elkhadiri', 'labiba.angona'], detail: 'intissar.elkhadiri allocated 340% above-average credits to labiba.angona ideas over 4 weeks.', score: 41, ts: '2025-06-22 11:45' },
];

export const TICKERS: TickerItem[] = [
  { sym: 'SPX', val: '5,842.31', chg: '+0.38%', up: true },
  { sym: 'NDX', val: '21,445.20', chg: '+0.52%', up: true },
  { sym: 'VIX', val: '14.22', chg: '-0.84%', up: false },
  { sym: 'DXY', val: '104.38', chg: '+0.12%', up: true },
  { sym: '10Y', val: '4.412%', chg: '-0.8bp', up: false },
  { sym: 'WTI', val: '78.54', chg: '-0.24%', up: false },
  { sym: 'NVDA', val: '875.50', chg: '+1.82%', up: true },
  { sym: 'MSFT', val: '425.20', chg: '+0.44%', up: true },
  { sym: 'TSLA', val: '248.50', chg: '-1.12%', up: false },
  { sym: 'META', val: '520.80', chg: '+0.73%', up: true },
];

export const TEMP_PASSWORD = 'Apex@2025';
export const WEEK_ID = 'W26-2025';
export const IDEA_LIMIT_PER_WEEK = 2;
